In [2]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [11, 12, 13]])

In [3]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [6]:
flat = arr.flatten()

In [7]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

In [8]:
flat[0]

1

In [10]:
flat[3: 6]

array([4, 5, 6])

In [11]:
flat[:5] # same as flat[0:5]

array([1, 2, 3, 4, 5])

In [12]:
flat[3:] # same as flat[3:13]

array([ 4,  5,  6,  7,  8,  9, 11, 12, 13])

In [13]:
flat[3:13]

array([ 4,  5,  6,  7,  8,  9, 11, 12, 13])

In [20]:
flat

array([     1,      2,      3, 444444,      5,      6,      7,      8,
            9,     11,     12,     13])

In [21]:
b = flat[3:7].copy() # This is not a slice because we are using copy method to get the copy

In [22]:
b

array([444444,      5,      6,      7])

In [24]:
b[0] = 444444666

In [25]:
b

array([444444666,         5,         6,         7])

In [26]:
flat

array([     1,      2,      3, 444444,      5,      6,      7,      8,
            9,     11,     12,     13])

In [27]:
arr = np.array([1, 54, 23, 53, 2, 3, 34, 5, 6])

In [28]:
arr[[1, 4, 6]]

array([54,  2, 34])

In [30]:
arr[arr>23]

array([54, 53, 34])

In [1]:
import numpy as np

In [34]:
matrix_3x3 = np.random.randint(low=0,high=10,size = (3,3))
print(matrix_3x3)

[[8 0 7]
 [5 6 9]
 [4 3 9]]


In [36]:
matrix_3x3.shape

(3, 3)

In [38]:
matrix_3x3.dtype

dtype('int64')

In [41]:
new=matrix_3x3.astype('float64')

In [42]:
new.dtype

dtype('float64')

In [77]:
fn = np.array([1,2,3,4,5,6])
inx= fn % 2 == 0
print(fn[inx])

[2 4 6]


In [79]:
array_1d = np.array([1,2,3,4,5,6,7,8,9])

In [82]:
array_1d.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [117]:
matrix_3x3 = np.random.randint(low=25,high=100,size = (1,15))
print(matrix_3x3)
print(matrix_3x3[matrix_3x3>50])

[[48 50 72 76 49 43 40 85 76 80 70 75 66 59 92]]
[72 76 85 76 80 70 75 66 59 92]


In [113]:
floats = np.array([1.1,2.2,3.3,4.4,5.5])
floats.dtype

dtype('float64')

In [93]:
floats.astype('int64')

array([1, 2, 3, 4, 5])